# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27a3aea7ad296daf8fe071fb3711a539fede5995a975af4b8524c237a1ceecd96a0b81f613e9d2b22cd97f6c53f85f25c3ff6fb6922992b4c9bcf4161cb02cd3

test:
  secret_key_base: 1bbeaf6e741074028a3d537efc308bed67d4e402860d8415ab9963fd0765c53eb0bb5d286bda6625b2724523983079b4e37cafd4442c90d0c60f59cbba0f304a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
